### Numpy Library
- Processing N-Dimensional arrays

In [9]:
import numpy as np

li=[1,2,3,'p']

a=np.array(li)

type(a)
a


array(['1', '2', '3', 'p'], dtype='<U11')

In [10]:
b=np.arange(15)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
rn=np.random.randint(1,100,size=15)
rn

array([85, 84, 47, 15, 57, 47, 91, 11, 84, 64, 48, 79, 76, 70, 22])

In [42]:
m3=np.random.randint(0,2,size=(3,3))
#m3
m3[2][0]

0

In [35]:
m4=np.random.randint(0,2,size=(3,3,3))
m4
m4[2][0][1]

1

In [34]:
m3.size # no of elements

m3.ndim # no of dimensions
m3.shape # shape of array
m3.dtype # type of data
m3.itemsize # 
m3.nbytes # capacity of total no of bytes

24

In [46]:
m3[0,2]

1

In [43]:
m3

array([[0, 1, 1],
       [1, 0, 1],
       [0, 1, 0]])